### ISSUE TITLE
wrapperClass only set by fragment, no other value will set it

### ISSUE THREAD

**Issue by pleasantone** [hugomods/images#35]
Would it be possible to allow a default for wrapperClass to be passed in as WrapperClass the same way we do ClassName?

I'm using images/image as a partial in my WIP imagegrid partial, and there is no way to default the wrapperClass to, for example, #float-left. We only allow a user to pass down the class of the <img>, not the <figure> or <picture>.

**Comment by razonyang** [comment]
I think we can pass the alignment via Filename, e.g. `example.jpg#float-left`.

**Comment by pleasantone** [comment]
That's what I'm doing, fine. No worries

**Comment by razonyang** [comment]
PR #39 adds more parameters for the `image` partial, you should be able to use the `Alignment` for this purpose since v0.9.0.
